export const GAME_STATUS_STOP = 'GAME_STATUS_STOP';
export const GAME_STATUS_ONGOING = 'GAME_STATUS_ONGOING';
export const GAME_STATUS_STOP_LOSE = 'GAME_STATUS_STOP_LOSE';
export const GAME_STATUS_STOP_WON = 'GAME_STATUS_STOP_WON';

